<a href="https://colab.research.google.com/github/tohnperfect/AIprototype2022/blob/main/Download_All_DB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install azure-data-tables

Collecting azure-data-tables
  Downloading azure_data_tables-12.3.0-py3-none-any.whl (110 kB)
     |████████████████████████████████| 110 kB 7.2 MB/s
Collecting azure-core<2.0.0,>=1.15.0
  Downloading azure_core-1.23.1-py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 44.4 MB/s
Collecting msrest>=0.6.21
  Downloading msrest-0.6.21-py2.py3-none-any.whl (85 kB)
     |████████████████████████████████| 85 kB 3.3 MB/s
Collecting typing-extensions>=4.0.1
  Downloading typing_extensions-4.1.1-py3-none-any.whl (26 kB)
Requirement already satisfied: six>=1.11.0 in /usr/local/lib/python3.7/dist-packages (from azure-core<2.0.0,>=1.15.0->azure-data-tables) (1.15.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.7/dist-packages (from azure-core<2.0.0,>=1.15.0->azure-data-tables) (2.23.0)
Collecting isodate>=0.6.0
  Downloading isodate-0.6.1-py2.py3-none-any.whl (41 kB)
     |████████████████████████████████| 41 kB 484 kB/s
Requirement already satisfied: requests-oauthlib>=0.5.0 in /usr/local/lib/python3.7/dist-packages (from msrest>=0.6.21->azure-data-tables) (1.3.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from msrest>=0.6.21->azure-data-tables) (2021.10.8)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.18.4->azure-core<2.0.0,>=1.15.0->azure-data-tables) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.18.4->azure-core<2.0.0,>=1.15.0->azure-data-tables) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.18.4->azure-core<2.0.0,>=1.15.0->azure-data-tables) (3.0.4)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from requests-oauthlib>=0.5.0->msrest>=0.6.21->azure-data-tables) (3.2.0)
Installing collected packages: typing-extensions, isodate, msrest, azure-core, azure-data-tables
  Attempting uninstall: typing-extensions
    Found existing installation: typing-extensions 3.10.0.2
    Uninstalling typing-extensions-3.10.0.2:
      Successfully uninstalled typing-extensions-3.10.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.8.0 requires tf-estimator-nightly==2.8.0.dev2021122109, which is not installed.
arviz 0.11.4 requires typing-extensions<4,>=3.7.4.3, but you have typing-extensions 4.1.1 which is incompatible.
Successfully installed azure-core-1.23.1 azure-data-tables-12.3.0 isodate-0.6.1 msrest-0.6.21 typing-extensions-4.1.1

In [2]:
from azure.data.tables import TableServiceClient
from azure.data.tables import TableEntity

In [3]:
table_service = TableServiceClient.from_connection_string(conn_str='DefaultEndpointsProtocol=https;AccountName=ovrdt;AccountKey=SlNrrCJDxIM+TlcZEEmatMltIgV1bGUpheTxJRFd7MGuCJw8kFvniuPEKurRyPnfx08+DnyJlNW7OOxxOPKGMA==;EndpointSuffix=core.windows.net')

In [4]:
table_client = table_service.get_table_client(table_name="ovrdtDB")

In [5]:
import pandas as pd

In [6]:
site_df = pd.read_excel('/content/drive/MyDrive/ovrdt data/hospital_list.xlsx')

In [7]:
site_df

,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
0,00001,สำนักงานสาธารณสุขจังหวัดสมุทรปราการ,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,1.0,ปากน้ำ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,สป,SPK
1,00002,สำนักงานสาธารณสุขจังหวัดนนทบุรี,4,สาขาพื้นที่(สระบุรี),12.0,นนทบุรี,1.0,เมืองนนทบุรี,4.0,บางกระสอ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,นบ,NBI
2,00003,สำนักงานสาธารณสุขจังหวัดปทุมธานี,4,สาขาพื้นที่(สระบุรี),13.0,ปทุมธานี,1.0,เมืองปทุมธานี,1.0,บางปรอก,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,ปท,PTE
3,00004,สำนักงานสาธารณสุขจังหวัดพระนครศรีอยุธยา,4,สาขาพื้นที่(สระบุรี),14.0,พระนครศรีอยุธยา,1.0,พระนครศรีอยุธยา,3.0,หอรัตนไชย,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,อย,AYA
4,00005,สำนักงานสาธารณสุขจังหวัดอ่างทอง,4,สาขาพื้นที่(สระบุรี),15.0,อ่างทอง,1.0,เมืองอ่างทอง,8.0,บ้านอิฐ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,อท,ATG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17098,99990,ศูนย์สุขภาพชุมชนโรงพยาบาลอุตรดิตถ์(สาขา 2 วัดท...,2,สาขาพื้นที่(พิษณุโลก),53.0,อุตรดิตถ์,1.0,เมืองอุตรดิตถ์,1.0,ท่าอิฐ,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,อต,UTT
17099,99991,ศูนย์สุขภาพชุมชนโรงพยาบาลกุยบุรี,5,สาขาพื้นที่(ราชบุรี),77.0,ประจวบคีรีขันธ์,2.0,กุยบุรี,1.0,กุยบุรี,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,ปข,PKN
17100,99993,ศูนย์สุขภาพชุมชนตำบลวัดเพลง,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,9.0,วัดเพลง,3.0,วัดเพลง,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,รบ,RBR
17101,99996,คลินิกทันตกรรม สสจ.ศรีสะเกษ,10,สาขาพื้นที่(อุบลราชธานี),33.0,ศรีสะเกษ,1.0,เมืองศรีสะเกษ,11.0,โพนข่า,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,ศก,SSK
17102,99998,ศูนย์สุขภาพชุมชนตำบลบางแพ,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,6.0,บางแพ,2.0,วังเย็น,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,รบ,RBR

In [8]:
from azure.data.tables import TableClient

In [9]:
alldb = list()

In [10]:
with TableClient.from_connection_string(conn_str='DefaultEndpointsProtocol=https;AccountName=ovrdt;AccountKey=SlNrrCJDxIM+TlcZEEmatMltIgV1bGUpheTxJRFd7MGuCJw8kFvniuPEKurRyPnfx08+DnyJlNW7OOxxOPKGMA==;EndpointSuffix=core.windows.net', table_name="ovrdtDB") as table_client:

    i = 0
    for entity in table_client.list_entities():
        alldb.append(entity)
        i += 1
        if i % 1000 == 0:
            print(i)

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000

In [11]:
db_df = pd.DataFrame(alldb)

In [13]:
db_df.head(30)

,user,RowKey,care,date,ov,phone,site,time,urine,pid,PartitionKey
0,test,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,04857,136FD222-FD9F-4E54-AE1F-7282A276B085,,2022-02-24,,"iPhone10,4",05310,10:50:32,,NaN,NaN
2,NaN,1E6D3D62-4C8A-4F8E-90D1-0DC5BC2752DF.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3450101576642,2D331FB0-CBA2-4586-A5B0-CB3CF44DD9FE,,2022-02-23,0,"iPhone13,4",05087,09:59:47,ปกติ (เหลืองใส),NaN,NaN
4,3450101576642,45197AF7-7CB4-470C-9ABB-37C092BD6B21,,2022-02-23,,"iPhone13,4",05087,09:44:06,ปกติ (เหลืองใส),NaN,NaN
5,08777,472EED3E-E2A7-4551-9249-D87747C68AFD,,2022-02-25,,"iPhone13,2",05248,10:14:46,,NaN,NaN
6,3450101576642,538F4D59-A921-46BF-82B0-E6834F98957E,,2022-02-23,,"iPhone13,4",05087,09:57:24,ปกติ (เหลืองใส),NaN,NaN
7,04857,73E96EE6-7660-4204-9914-92112603C514,,2022-02-24,,"iPhone10,4",05310,11:14:21,,NaN,NaN
8,5799,7EE1D55E-56FD-4AF9-B183-5413C076BC11,,2022-02-22,,"iPhone13,3",14843,10:14:53,,NaN,NaN
9,3450101576642,9AF8428C-0616-47DE-AB4C-54F31EA31979,,2022-02-23,0,"iPhone13,4",05087,10:11:06,ปกติ (เหลืองใส),NaN,NaN
10,3450101576642,B7C1D24C-8090-4C2F-BC04-7CC4D09663DC,,2022-02-23,0,"iPhone13,4",05087,09:58:42,ปกติ (เหลืองใส),NaN,NaN
11,08777,C23A546B-EB6E-4DB4-93FA-2F9A7A85AEE9,,2022-02-25,,"iPhone13,2",05248,10:14:32,,NaN,NaN
12,11111,C42C6F97-4388-4C03-A0AB-84F21FAED2C2,,2022-02-27,,"iPhone13,3",22222,17:39:35,,NaN,NaN
13,3450101576642,C5E5C877-D7BC-4137-A328-8F350932B9DF,,2022-02-23,0,"iPhone13,4",05087,09:58:03,ปกติ (เหลืองใส),NaN,NaN
14,3450101576642,D94E9A26-80AF-4A24-A4DC-A4F78414694C,,2022-02-23,0,"iPhone13,4",05087,10:00:11,ปกติ (เหลืองใส),NaN,NaN
15,3450101576642,DAF6A435-1DA8-4E80-9CDE-5E39DB2EB80D,,2022-02-23,0,"iPhone13,4",05087,09:59:13,ปกติ (เหลืองใส),NaN,NaN
16,3450101576642,DEABB305-D5EE-4B72-A413-60EC5FCA5C2E,,2022-02-23,,"iPhone13,4",05087,09:56:31,,NaN,NaN
17,11111,F1C573A6-D353-44D6-8046-052237DA9220,,2022-02-27,,"iPhone13,3",22222,17:30:18,,NaN,NaN
18,NaN,F3D23A09-D9B8-4EDC-80B3-0152DC54F126,,NaN,,"iPhone12,1",,NaN,,,NaN
19,NaN,acdywyebte.png,,NaN,,Samsung SM-N950F,,NaN,,,NaN
20,,aczroqxlzp.png,,2022-02-23,0,Samsung SM-A305F,,09:27:30,ปกติ (เหลืองใส),NaN,NaN
21,,adhqvjxzmf.png,,NaN,,Xiaomi 21061119AG,,NaN,,NaN,NaN
22,,aksxskngcv.png,,2022-02-19,,OPPO CPH1989,,09:29:46,,NaN,NaN
23,,aqawlmgiay.png,,NaN,,OPPO CPH1989,,NaN,,NaN,NaN
24,,aqgzagjmut.png,,2022-02-26,0,HUAWEI STK-L22,05435,10:38:22,ปกติ (เหลืองใส),NaN,NaN
25,,bauvbwzbtv.png,,2022-02-26,4,HUAWEI STK-L22,,09:55:24,ปกติ (เหลืองใส),NaN,NaN
26,,bdvpqurtvu.png,,2022-02-22,3,Samsung SM-J415F,05082,12:59:06,ปกติ (เหลืองใส),NaN,NaN
27,,becehpticx.png,,2022-03-17,,OPPO CPH2113,,10:14:55,,NaN,NaN
28,,bgjqcjizmu.png,,NaN,,OPPO CPH2197,,NaN,,NaN,NaN
29,,bhnsgchboh.png,,2022-02-23,0,Samsung SM-A305F,,09:35:20,ปกติ (เหลืองใส),NaN,NaN

In [14]:
db_df.tail(30)

,user,RowKey,care,date,ov,phone,site,time,urine,pid,PartitionKey
39904,NaN,AC3B0538-25A2-4193-B7C1-F948123A04C8,,NaN,1,"iPhone12,1",01234,NaN,ปกติ (เหลืองใส),00006,w.soodboonma
39905,NaN,sakuzggmio.png,0,NaN,2,Samsung SM-G998B,eedd,NaN,ปกติ (เหลืองใส),1wws,wsd
39906,NaN,7A0FBD1B-0C96-47F2-B05B-1C869CDA09B8,,NaN,2,"iPhone13,4",dews,NaN,ขุ่น,wwdd,wwdc
39907,NaN,gqoqlxuzls.png,,NaN,3,Samsung SM-G998B,11www,NaN,"ปกติ (เหลืองใส), มีเม็ดเลือดแดง",1122s,wwdd
39908,NaN,gvwwlsjwlq.png,,NaN,1,Samsung SM-G998B,11www,NaN,"ขุ่น, มีเม็ดเลือดแดง",1qsd,wwdd
39909,22,sgitnfuked.png,,NaN,4,Samsung SM-G998B,www,NaN,มีตะกอน,NaN,wwe
39910,22,cjqmqywwsk.png,,NaN,0,Samsung SM-G998B,www,NaN,มีเลือดปน,NaN,www
39911,www,cyzfuzvxyz.png,,2022-02-17,3,Samsung SM-N950F,www,00:01:08,มีเม็ดเลือดแดง,NaN,www
39912,ttest,crqcufokmn.png,,2022-02-21,2,Samsung SM-G998B,test,14:23:45,ขุ่น,NaN,x001
39913,ttest,gzxgflnowr.png,,2022-02-21,2,Samsung SM-G998B,test,14:23:43,ขุ่น,NaN,x001
39914,NaN,1CD6454A-C3DA-4D30-A314-DE90D9C1A40F,,NaN,,"iPhone13,4",xxx,NaN,ขุ่น,xxx,xxx
39915,xxx,jytlopevha.png,,2022-02-17,3,Samsung SM-N950F,xxx,00:01:06,ปกติ (เหลืองใส),NaN,xxx
39916,12345,zgvicawbkg.png,,NaN,2,Samsung SM-G998B,xxxxx,NaN,ปกติ (เหลืองใส),NaN,xxxxx
39917,NaN,bmrxfmjtsm.png,1,NaN,2,Samsung SM-G998B,xxxxxx,NaN,ปกติ (เหลืองใส),xxxxxx,xxxxxx
39918,NaN,D267F0D8-AC13-48E4-A09E-98A959E90076,,NaN,2,"iPhone12,1",xxxxxx,NaN,ปกติ (เหลืองใส),xxxxxx,xxxxxxx
39919,NaN,DA0AA1C7-E040-4160-965D-1DCCF06CC137,ใช้ Praziquantel,NaN,2,"iPhone12,1",xxxxxxx,NaN,ปกติ (เหลืองใส),xxxxxxx,xxxxxxx
39920,NaN,A346EFC2-9B5B-4153-BD06-AE615FFE4244,,NaN,,"iPhone8,2",t,NaN,ขุ่น,h,y
39921,yyy,ivccsksowb.png,,2022-02-17,2,Samsung SM-N950F,yyy,08:41:05,มีเม็ดเลือดแดง,NaN,yyy
39922,zzz,psudrnccsh.png,,2022-02-17,2,Samsung SM-N950F,zzz,08:41:04,มีตะกอน,NaN,zzz
39923,NaN,88D7B3D2-9266-436E-9AFF-4A8878B49A3B,ได้รับยา ยาฆ่าพยาธิใบไม้ตับ (Praziquantel),NaN,1,"iPhone12,1",0123,NaN,ปกติ (เหลืองใส),5,กนกพร พินิจลึก
39924,NaN,84885775-8E1D-45E1-A9C2-941CAC3F1814,,NaN,2,"iPhone9,4",01234,NaN,ปกติ (เหลืองใส),3,จิ๊บ
39925,NaN,D0E593D6-5517-463E-8440-6379F242031E,,NaN,1,"iPhone13,3",ถถ,NaN,มีตะกอน,ภ,ถ
39926,NaN,C543CE9F-3E07-4A9E-BF38-4D9282D49D84,,NaN,1,"iPhone9,3",123,NaN,ปกติ (เหลืองใส),1234,พพ
39927,NaN,lkwfdvltek.png,,NaN,2,Samsung SM-A307GN,01234,NaN,ปกติ (เหลืองใส),7,พัชราภรณ์
39928,NaN,txslrhofvq.png,1,NaN,1,Samsung SM-N935F,Hosp01234,NaN,ปกติ (เหลืองใส),00006,มยุรา
39929,NaN,6B5FA20F-190E-4021-8547-C12308024C6C,,NaN,,"iPhone13,4",01234,NaN,,5,เกษศิรินทร์ ไชยลาภ
39930,NaN,F48C51C0-A345-40D6-93F4-46213267E1B1,,NaN,2,"iPhone10,5",01234,NaN,ปกติ (เหลืองใส),5,เถลิงเกียรติ เสริฐเลิศ
39931,NaN,A986BDAA-6D7C-4017-8E62-A3C104E946B9,,NaN,1,"iPhone13,4",01234,NaN,ปกติ (เหลืองใส),1,เสรี
39932,NaN,bbuogxulur.png,,NaN,,Samsung SM-A115F,01234,NaN,,1,เสรี
39933,NaN,zttpqogiso.png,,NaN,1,Samsung SM-A115F,01234,NaN,ปกติ (เหลืองใส),1,เสรี

In [15]:
db_df.to_csv('alldb.csv')

In [28]:
db_df.dropna(subset=['RowKey','phone','time','PartitionKey']).head(30)

,user,RowKey,care,date,ov,phone,site,time,urine,pid,PartitionKey
185,85879,shmpdrmtgc.png,,2022-03-24,0,OPPO CPH2293,05194,13:08:39,มีตะกอน,NaN,0000
186,45-161,D2CABB8C-533B-450A-AFA6-B693749CC1C6,,2022-02-23,0,"iPhone11,8",04312,09:45:28,ปกติ (เหลืองใส),NaN,0-1528
187,45-161,57A5F06C-C840-49EA-9514-A30D3C897CC8,,2022-02-23,0,"iPhone11,8",04312,10:06:45,ปกติ (เหลืองใส),NaN,0-1544
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,,2022-02-25,0,"iPhone13,1",04999,14:22:22,ปกติ (เหลืองใส),NaN,0000
190,06223,kfpwuaqldj.png,,2022-03-23,0,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),NaN,00000
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,,2022-03-30,4,"iPhone12,3",06307,14:46:08,ปกติ (เหลืองใส),NaN,00001
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,,2022-03-30,4,"iPhone14,3",05328,15:27:45,ปกติ (เหลืองใส),NaN,00001
193,95821,1914EE67-CD8F-47EE-A968-2772911AA5DF,,2022-03-30,3,"iPhone13,4",06302,10:16:46,ปกติ (เหลืองใส),NaN,00001
194,13361,1A219EE7-3647-4D7D-A8C0-AE638E69D889,,2022-03-29,3,"iPhone9,4",05059,12:26:38,ปกติ (เหลืองใส),NaN,00001
195,28241,1AFBC992-AF2F-4F97-AE6D-443F30ED8402,,2022-03-31,0,"iPhone13,3",06334,14:57:41,ปกติ (เหลืองใส),NaN,00001
196,41340,1C640780-7513-43C0-B1E4-4A535DA468F3,,2022-03-30,3,"iPhone14,5",06288,10:28:02,ปกติ (เหลืองใส),NaN,00001
197,06277,1DDA8B23-D1EA-4E15-AE70-1E7FE53733B6,,2022-03-25,2,"iPhone14,3",06277,10:13:51,ปกติ (เหลืองใส),NaN,00001
198,22119,1FBE544D-7313-43EA-95EF-91DAD0513808,,2022-04-01,4,"iPhone8,1",06261,15:40:17,ปกติ (เหลืองใส),NaN,00001
199,19911,22E333B1-A8D4-4FCB-8304-7BD2C3D9C94A,,2022-03-30,0,"iPhone12,5",06319,09:32:46,ปกติ (เหลืองใส),NaN,00001
200,99771,267232EA-5B0D-4783-8449-16687A62C5B7,,2022-03-22,0,"iPhone10,6",05396,10:35:33,ปกติ (เหลืองใส),NaN,00001
201,89195,27A826ED-D57D-4386-8A3C-9CFD13297B8B,,2022-03-30,4,"iPhone9,3",06267,10:08:32,ปกติ (เหลืองใส),NaN,00001
202,59476,2AAA9DE2-24E6-4F41-B02E-0CB610C906C6,,2022-03-25,4,"iPhone9,4",05000,11:14:25,สีฟ้า หรือน้ำเงิน,NaN,00001
203,18041,3FBB8FE8-F3EE-4307-8E01-406D7A1B2488,,2022-03-28,2,"iPhone14,3",11158,10:12:10,ปกติ (เหลืองใส),NaN,00001
204,14360,41AE352F-77A0-4D26-B39C-6A09B39576BA,,2022-03-31,0,"iPhone8,2",04405,14:11:05,ปกติ (เหลืองใส),NaN,00001
205,93884,448CF555-676C-4A89-BF0D-B1F2FB5BF97A,,2022-03-25,4,"iPhone12,3",06280,14:06:18,ปกติ (เหลืองใส),NaN,00001
206,24986,44E5D0C4-9195-47FC-82C3-CF9A711D85AB,,2022-03-28,1,"iPhone14,3",06278,11:49:13,ปกติ (เหลืองใส),NaN,00001
207,16085,49A9B05F-9B2F-49B9-99D7-CC3A60836EE1,,2022-03-30,3,"iPhone13,2",06299,13:11:51,ปกติ (เหลืองใส),NaN,00001
208,27096,4D1F5F3E-E557-4F64-BEB7-D4FBCADFA43F,,2022-03-30,0,"iPhone14,5",11160,14:56:46,ปกติ (เหลืองใส),NaN,00001
209,60847,52421C45-3625-4E62-B681-158CF7049DC7,,2022-03-28,3,"iPhone14,3",06298,10:23:45,ปกติ (เหลืองใส),NaN,00001
210,00001,540553CD-1EAB-4252-A64E-F96A8390CE10,,2022-03-28,2,"iPad13,6",10360,12:24:15,ปกติ (เหลืองใส),NaN,00001
211,74891,594A7093-AB5F-4A64-8B74-E336ED81A444,,2022-04-01,2,"iPhone12,8",05055,15:15:35,มีตะกอน,NaN,00001
212,38381,5F4622C8-96BE-4A29-A3CE-4FE18B912F7A,,2022-03-28,0,"iPhone12,1",06276,11:25:52,ปกติ (เหลืองใส),NaN,00001
213,40059,5F8D255F-B0F5-4CE5-9607-7916E394173D,,2022-03-18,2,"iPad13,1",05052,11:36:13,ใสเป็นน้ำเปล่า,NaN,00001
214,77254,638E4F0D-2AB7-4774-8458-ED6B394B3EAE,,2022-03-30,3,"iPhone13,4",06302,09:54:58,ปกติ (เหลืองใส),NaN,00001
215,63485,645ABE09-DE04-4093-BCC1-44F481FE9605,,2022-03-17,0,"iPhone12,1",05332,11:43:37,ปกติ (เหลืองใส),NaN,00001

In [29]:
import requests
import json

In [30]:
URL = 'https://tools.cascap.in.th/api/ai/reg/'

In [40]:
row = 0
sid=db_df.iloc[row,:]['site']
pid=db_df.iloc[row,:]['PartitionKey']
print(sid,pid)

nan nan

In [41]:
 
#payload = {'main':str(msg).split('/')[-2],'fname':str(msg).split('/')[-1]}
payload = {
    'site':sid,
    'pid':pid,
    'auth':{
        'user':'3101600271140',
        'key':'Rl85OXBpRVUwb3RBWXB5T3huR2pKTHNLWnJLdkgzRmo='
    },
    'apps':{
        'name':'dashboard',
        'version':'0.0.1'
    }
}

In [42]:
print(json.dumps(payload))

{"site": NaN, "pid": NaN, "auth": {"user": "3101600271140", "key": "Rl85OXBpRVUwb3RBWXB5T3huR2pKTHNLWnJLdkgzRmo="}, "apps": {"name": "dashboard", "version": "0.0.1"}}

In [43]:
ret_predict = requests.post(URL, json=payload)
result = ret_predict.json()

In [44]:
result

{'data': {'msg': 'Invalid'},
 'jsondata': None,
 'key': None,
 'pid': None,
 'site': None,
 'status': 'FAIL',
 'user': None}

In [39]:
print(result['data']['title'],result['data']['age'])

นางสาว 47

In [57]:
title = list()
age = list()
for r in db_df.iterrows():
    sid=r[1]['site']
    pid=r[1]['PartitionKey']
    if (len(str(sid)) == 5) & (len(str(pid)) == 5) :
        payload = {
        'site':sid,
        'pid':pid,
        'auth':{
            'user':'3101600271140',
            'key':'Rl85OXBpRVUwb3RBWXB5T3huR2pKTHNLWnJLdkgzRmo='
        },
        'apps':{
            'name':'dashboard',
            'version':'0.0.1'
        }
        }
        ret_predict = requests.post(URL, json=payload)
        result = ret_predict.json()
        if result['status'] == 'OK':
            title.append(result['data']['title'])
            age.append(result['data']['age'])
        else:
            title.append('no data')
            age.append('no data')
    else:
        title.append('data is not completed')
        age.append('data is not completed')

KeyboardInterrupt: ignored

In [58]:
len(title)

3099

In [59]:
len(age)

3099